In [ ]:
# LSTM ile SMS analizi

import pandas as pd
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM
from sklearn.model_selection import train_test_split

In [ ]:
df=pd.read_csv("/content/TurkishSMSCollection.csv",on_bad_lines='skip',delimiter=";")
df.head(10)

                                             Message  Group GroupText
0                                           125 lira      2    Normal
1              Baskanin aksam toplantısi fenaymis :)      2    Normal
2                Bilal yalçnlara ne zaman gidiyoruz?      2    Normal
3  BiP ile mesajlarimi aninda, daha eglenceli gon...      1      Spam
4  DIGITURKTEN FIRSAT! SiZE OZEL YIL SONUNA KADAR...      1      Spam
5  İyi ya dokuz eylül iyidir arş.gör falan kovala ;)      2    Normal
6  İyiyim teşekkürler oturuyoruz nazarda arkadaşl...      2    Normal
7            Kapatamıyorun ayarlara girmem lazım :)       2    Normal
8                 Menüye girsem görünür mü acaba ??       2    Normal
9                Önemli değil hocam iyi akşamlar ;)       2    Normal

In [ ]:
df['label']=np.where(df['Group']==1,1,0)

In [ ]:
df.head(3)

                                 Message  Group GroupText  label
0                               125 lira      2    Normal      0
1  Baskanin aksam toplantısi fenaymis :)      2    Normal      0
2    Bilal yalçnlara ne zaman gidiyoruz?      2    Normal      0

In [ ]:
tokenizer=Tokenizer(num_words=500)
tokenizer.fit_on_texts(df['Message'])
sequences=tokenizer.texts_to_sequences(df['Message'])

pad=pad_sequences(sequences,maxlen=20)
y=df['label'].values

x_train,x_test,y_train,y_test=train_test_split(pad,y,test_size=0.2)

model=Sequential()

model.add(Embedding(500,100,input_length=20))
model.add(LSTM(64,dropout=0.2,recurrent_dropout=0.2))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=12,batch_size=64)

Epoch 1/12

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

60/60 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.8573 - loss: 0.4176 - val_accuracy: 0.9874 - val_loss: 0.0478
Epoch 2/12
60/60 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9813 - loss: 0.0578 - val_accuracy: 0.9926 - val_loss: 0.0242
Epoch 3/12
60/60 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - accuracy: 0.9897 - loss: 0.0363 - val_accuracy: 0.9926 - val_loss: 0.0164
Epoch 4/12
60/60 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9932 - loss: 0.0206 - val_accuracy: 0.9937 - val_loss: 0.0141
Epoch 5/12
60/60 ━━━━━━━━━━━━━━━━━━━━ 4s 59ms/step - accuracy: 0.9952 - loss: 0.0149 - val_accuracy: 0.9947 - val_loss: 0.0120
Epoch 6/12
60/60 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9963 - loss: 0.0102 - val_accuracy: 0.9947 - val_loss: 0.0116
Epoch 7/12
60/60 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9972 - loss: 0.0088 - val_accuracy: 0.9947 - val_loss: 0.0121
Epoch 8/12
60/60 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9983 - loss: 0.0052 - val_accuracy: 0.9958 - val_loss: 0.0121
Epoch 9/12
60/60 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.9994 - loss: 0.0030 - val_accuracy: 0.9937 - val_loss: 0.0132
Epoch 10/12
60/60 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9996 - loss: 0.0027 - val_accuracy: 0.9968 - val_loss: 0.0115
Epoch 11/12
60/60 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9992 - loss: 0.0026 - val_accuracy: 0.9947 - val_loss: 0.0145
Epoch 12/12
60/60 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.9958 - val_loss: 0.0132

In [ ]:
tahmin="günaydın nasılsın ? bugün okula gelecek misin ?"

tahmin_array=tokenizer.texts_to_sequences([tahmin])
tahmin_array=pad_sequences(tahmin_array,maxlen=20)

model.predict(tahmin_array)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

array([[5.479717e-05]], dtype=float32)

In [ ]:
model.save('sms.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.